language: java
jdk:
  - oraclejdk8
env:
  global:
  - TERM=dumb
branches:
  only: 
  - master
install: mvn clean install cobertura:cobertura
notifications:
  slack:
    on_success: change
    on_failure: change
    slack: hellowood:3qHqpWCi2LQV4MsQYPsHJBK6
before_install:
  - pip install --user codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
