sudo: required
dist: trusty
cache:
  directories:
  - "$HOME/.m2"
language: java
jdk:
  - oraclejdk8
branches:
  only: 
  - master
install: mvn clean install cobertura:cobertura
before_script:
- echo "MAVEN_OPTS='-Xmx1024m -XX:MaxPermSize=256m'" > ~/.mavenrc
before_install:
  - pip install --user codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
